# -*- coding: utf-8 -*-
"""HavaDurumuUygulaması.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFy-qCL5isqYMD5d30K97yCrBfEDoiAW
"""

class Sehir:
    def __init__(self, isim, sicaklik):
        self.isim = isim
        self.sicaklik = sicaklik

    def tavsiye(self):
        if self.sicaklik < 0:
            return "Soğuk, sıkı giyin, eldivensiz çıkma."
        elif 0 <= self.sicaklik < 15:
            return "Serin, mont almayı unutmayın."
        elif 15 <= self.sicaklik < 20:
            return "Hava güzel rahat giyin."
        elif 20 <= self.sicaklik < 40 :
            return "Güneş kremini sürmeyi unutma."
        else:
            return "Bu havada dışarı çıkılmamalı."


class HavaDurumuUygulamasi:
    def __init__(self):
        self.sehirler = {}

    def sehir_ekle(self, isim, sicaklik):
        if isim in self.sehirler:
            return f"{isim} zaten kayıtlı."
        self.sehirler[isim] = Sehir(isim, sicaklik)
        return f"{isim} başarıyla eklendi."

    def hava_durumu_sorgula(self, isim):
        sehir = self.sehirler.get(isim)
        if not sehir:
            return f"{isim} şehir kaydı bulunamadı."
        return f"{isim} için sıcaklık: {sehir.sicaklik}°C. {sehir.tavsiye()}"

if __name__ == "__main__":
    uygulama = HavaDurumuUygulamasi()

    while True:
        print("\n1. Şehir ve sıcaklık ekle")
        print("2. Hava durumu tavsiyesi al")
        print("3. Çıkış")
        secim = input("Seçiminizi yapın (1/2/3): ")

        if secim == "1":
            isim = input("Şehir ismini girin: ")
            try:
                sicaklik = float(input(f"{isim} için sıcaklık değerini girin (°C): "))
                print(uygulama.sehir_ekle(isim, sicaklik))
            except ValueError:
                print("Lütfen geçerli bir sıcaklık değeri girin.")
        elif secim == "2":
            isim = input("Sorgulamak istediğiniz şehrin ismini girin: ")
            print(uygulama.hava_durumu_sorgula(isim))
        elif secim == "3":
            print("Tekrar görüşmek üzere, mutlu günler")
            break
        else:
            print("Geçersiz seçim, lütfen tekrar deneyin.")